controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

#app_newsletter:
#    path: /newsletter
#    methods: ['POST']
#    controller: App\Controller\NewsletterController::app_newsletter
